import{firebaseConfig,ADMIN_UID}from"./firebase-config.js";
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.10.0/firebase-app.js";
import{getDatabase,ref,onValue,set,update,push,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.10.0/firebase-database.js";
import{getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.10.0/firebase-auth.js";
const $=id=>document.getElementById(id),esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const C=[["medizin","🚑 Medizinischer Notfall"],["brand","🔥 Brand / Rauch"],["vu","🚗 Verkehrsunfall"],["abc","☣️ ABC / Gefahrgut"],["thl","🛠️ Technische Hilfeleistung"],["wasser","🌊 Wasser / Eis"],["sturz","⬇️ Sturz / Höhe"],["gewalt","⚠️ Gewalt"],["vergiftung","🧪 Vergiftung"],["strom","⚡ Strom"],["geburt","👶 Geburtshilfe"],["sonst","❓ Sonstiges"]];
const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app);let cat={},nar={},rr={},sug={},user=null,kind=null,A={},idx=0;
function admin(){return user&&ADMIN_UID&&!ADMIN_UID.startsWith("HIER_")&&user.uid===ADMIN_UID}
function init(){ $("cats").innerHTML=C.map(([id,n])=>`<button class="cat" data-id="${id}">${n}</button>`).join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>start(b.dataset.id));["qc","nc","rc"].forEach(x=>$(x).innerHTML=C.map(([id,n])=>`<option value="${id}">${n}</option>`).join("")); onValue(ref(db,"catalog"),x=>{cat=x.val()||{};$("status").textContent="● Firebase verbunden"},e=>$("status").textContent="● Firebase Fehler: "+e.code);onValue(ref(db,"notarzt_rules"),x=>nar=x.val()||{});onValue(ref(db,"resource_rules"),x=>rr=x.val()||{});onValue(ref(db,"suggestions"),x=>sug=x.val()||{}); }
function qs(){return Object.entries(cat[kind]?.questions||{}).map(([id,q])=>({id,...q})).filter(q=>q.active!==false&&(!q.when||String(A[q.when.questionId])===String(q.when.value))).sort((a,b)=>(a.order||100)-(b.order||100))}
function start(k){kind=k;A={};idx=0;$("home").hidden=true;$("call").hidden=false;$("title").textContent=C.find(x=>x[0]===k)[1];render()}
function render(){let L=qs(),q=L[idx];if(!q){$("question").innerHTML="<h2>Noch keine passenden Fragen.</h2>";side();return}let h=`<h2>${esc(q.text)}</h2>`;if(q.type==="choice"){h+=(q.options||[]).map(o=>`<button class="answer">${esc(o)}</button>`).join("");$("question").innerHTML=h;document.querySelectorAll(".answer").forEach((b,i)=>b.onclick=()=>answer(q.id,q.options[i]))}else{h+=`<input id="free" type="${q.type==="number"?"number":"text"}"><div id="suggest" class="suggest"></div><button id="savefree">Antwort übernehmen →</button>`;$("question").innerHTML=h;let f=$("free");if(q.suggestionGroup){let draw=()=>{let w=Object.values(sug[q.suggestionGroup]||{}).filter(x=>!f.value||String(x).toLowerCase().includes(f.value.toLowerCase())).slice(0,10);$("suggest").innerHTML=w.map(x=>`<div>${esc(x)}</div>`).join("");$("suggest").querySelectorAll("div").forEach((d,i)=>d.onclick=()=>{f.value=w[i];$("suggest").innerHTML=""})};f.oninput=draw;f.onfocus=draw}$("savefree").onclick=()=>answer(q.id,f.value)}$("prev").disabled=idx===0;side()}
function answer(id,v){A[id]=v;if(idx<qs().length-1){idx++;render()}else side()}
function rules(src){return Object.entries(src).map(([id,x])=>({id,...x})).filter(x=>x.active!==false&&(!x.category||x.category===kind)&&String(A[x.questionId])===String(x.value))}
function side(){let L=qs();$("answers").innerHTML=L.filter(q=>A[q.id]!=null).map(q=>`<div class="item"><small>${esc(q.text)}</small><br>${esc(A[q.id])}</div>`).join("")||"Noch keine Angaben.";let n=rules(nar);$("na").innerHTML=n.length?n.map(x=>"• "+esc(x.reason||x.id)).join("<br>"):"Keine Regel ausgelöst.";let set=new Set;rules(rr).forEach(x=>(x.resources||[]).forEach(r=>set.add(r)));if(n.length)set.add("🚨 NEF / NOTARZT");$("res").innerHTML=set.size?[...set].map(x=>`<span class="tag">${esc(x)}</span>`).join(""):"Noch keine ausreichenden Angaben."}
async function finish(){side();if(user){let n=rules(nar),set=new Set;rules(rr).forEach(x=>(x.resources||[]).forEach(r=>set.add(r)));if(n.length)set.add("🚨 NEF / NOTARZT");await set(push(ref(db,"call_history/"+user.uid)),{category:kind,answers:A,notarzt:n.map(x=>({id:x.id,reason:x.reason||""})),resources:[...set],createdAt:serverTimestamp()})}alert("Auswertung abgeschlossen. Bei angemeldeten Benutzern wurde die Abfrage gespeichert.")}
function must(){if(!admin())throw Error("Keine Administratorberechtigung. ADMIN_UID prüfen.")}
async function saveQ(){must();let id=$("qid").value.trim(),text=$("qt").value.trim();if(!id||!text)throw Error("Frage-ID und Frage erforderlich.");let d={text,type:$("qtype").value,options:$("qo").value.split("\\n").map(x=>x.trim()).filter(Boolean),order:Number($("order").value||100),active:true,suggestionGroup:$("sg").value.trim()||null};if($("wq").value.trim()&&$("wv").value.trim())d.when={questionId:$("wq").value.trim(),value:$("wv").value.trim()};await set(ref(db,`catalog/${$("qc").value}/questions/${id}`),d);alert("Gespeichert");}
async function saveN(){must();let id=$("nid").value.trim();await set(ref(db,"notarzt_rules/"+id),{active:true,category:$("nc").value,questionId:$("nq").value.trim(),value:$("nv").value.trim(),reason:$("nr").value.trim()});alert("Gespeichert")}
async function saveR(){must();let id=$("rid").value.trim();await set(ref(db,"resource_rules/"+id),{active:true,category:$("rc").value,questionId:$("rq").value.trim(),value:$("rv").value.trim(),resources:$("rr").value.split("\\n").map(x=>x.trim()).filter(Boolean)});alert("Gespeichert")}
async function saveS(){must();await set(push(ref(db,"suggestions/"+$("sgrp").value.trim())),$("stxt").value.trim());alert("Gespeichert")}
async function seed(){must();await update(ref(db),{
"catalog/medizin/questions/problem":{text:"Was ist das hauptsächliche Problem?",type:"choice",options:["Bewusstseinsstörung","Atemnot","Thoraxschmerz","Neurologische Ausfälle","Krampfanfall","Starke Blutung","Diabetes / Stoffwechsel","Sonstiges"],order:10,active:true},
"catalog/medizin/questions/bewusstsein":{text:"Wie ist das Bewusstsein?",type:"choice",options:["Wach und orientiert","Verwirrt / desorientiert","Somnolent","Soporös","Bewusstlos"],order:20,active:true},
"catalog/medizin/questions/atmung":{text:"Wie ist die Atmung?",type:"choice",options:["Normal","Dyspnoe","Ausgeprägte/zunehmende Dyspnoe","Keine normale Atmung","Atemstillstand"],order:30,active:true},
"catalog/medizin/questions/vorerkrankungen":{text:"Sind relevante Vorerkrankungen bekannt?",type:"choice",options:["Ja","Nein","Unklar"],order:40,active:true},
"catalog/medizin/questions/vorerkrankung_text":{text:"Welche Vorerkrankungen?",type:"text",order:50,active:true,suggestionGroup:"vorerkrankungen",when:{questionId:"vorerkrankungen",value:"Ja"}},
"catalog/brand/questions/brandart":{text:"Was ist passiert?",type:"choice",options:["Feuer sichtbar","Rauchentwicklung","Brandgeruch","Explosion"],order:10,active:true},
"catalog/brand/questions/personen":{text:"Sind Personen betroffen oder in Gefahr?",type:"choice",options:["Ja","Nein","Unklar"],order:20,active:true},
"catalog/vu/questions/vuart":{text:"Was ist passiert?",type:"choice",options:["Zusammenstoß","Frontalzusammenstoß","Überschlag","Motorradunfall"],order:10,active:true},
"catalog/vu/questions/eingeklemmt":{text:"Ist eine Person eingeklemmt?",type:"choice",options:["Ja","Nein","Unklar"],order:20,active:true},
"notarzt_rules/bewusstlos":{active:true,category:"medizin",questionId:"bewusstsein",value:"Bewusstlos",reason:"Schwere Bewusstseinsstörung – Bewusstlosigkeit"},
"notarzt_rules/atemstillstand":{active:true,category:"medizin",questionId:"atmung",value:"Atemstillstand",reason:"Keine Spontanatmung / Atemstillstand"},
"notarzt_rules/dyspnoe":{active:true,category:"medizin",questionId:"atmung",value:"Ausgeprägte/zunehmende Dyspnoe",reason:"Ausgeprägte oder zunehmende Dyspnoe"},
"notarzt_rules/eingeklemmt":{active:true,category:"vu",questionId:"eingeklemmt",value:"Ja",reason:"Einklemmung nach Verkehrsunfall"},
"resource_rules/medizin_rtw":{active:true,category:"medizin",questionId:"problem",value:"Atemnot",resources:["🚑 RTW"]},
"resource_rules/vu_thl":{active:true,category:"vu",questionId:"eingeklemmt",value:"Ja",resources:["🚒 Feuerwehr – Technische Hilfeleistung","🚑 RTW"]},
"suggestions/vorerkrankungen/a":"Diabetes mellitus","suggestions/vorerkrankungen/b":"Diabetes Typ 1","suggestions/vorerkrankungen/c":"Diabetes Typ 2","suggestions/vorerkrankungen/d":"Asthma bronchiale","suggestions/vorerkrankungen/e":"COPD","suggestions/vorerkrankungen/f":"KHK","suggestions/vorerkrankungen/g":"Herzinsuffizienz","suggestions/vorerkrankungen/h":"Epilepsie"
});alert("Grunddaten gespeichert")}
$("back").onclick=()=>{$("call").hidden=true;$("home").hidden=false};$("prev").onclick=()=>{if(idx){idx--;render()}};$("finish").onclick=()=>finish().catch(e=>alert(e.message));$("login").onclick=()=>$("modal").hidden=false;$("cancel").onclick=()=>$("modal").hidden=true;$("dologin").onclick=async()=>{try{$("err").textContent="";await signInWithEmailAndPassword(auth,$("email").value.trim(),$("pw").value)}catch(e){$("err").textContent=e.message}};$("logout").onclick=()=>signOut(auth);document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.hidden=true);$("tab-"+b.dataset.tab).hidden=false});$("saveq").onclick=()=>saveQ().catch(e=>alert(e.message));$("saven").onclick=()=>saveN().catch(e=>alert(e.message));$("saver").onclick=()=>saveR().catch(e=>alert(e.message));$("saves").onclick=()=>saveS().catch(e=>alert(e.message));$("seed").onclick=()=>seed().catch(e=>alert(e.message));onAuthStateChanged(auth,u=>{user=u;$("admin").hidden=!admin();$("login").hidden=!!u;$("logout").hidden=!u;if(u)$("modal").hidden=true});init();
