export const EHSI_SECTIONS = [
  {
    id:'rettungsdienst', icon:'🚑', title:'Rettungsdienst',
    items:[
      {title:'Notarztindikationen / NEF-Hinweise',text:'Kurzübersicht für die Disposition. Die konkrete Notarztentscheidung bleibt an den örtlich hinterlegten NAIK-/Leitstellenregeln gebunden.',links:[['Bundesärztekammer – NAIK 2023','https://www.bundesaerztekammer.de/fileadmin/user_upload/wissenschaftlicher-beirat/Veroeffentlichungen/Bek_BAEK_Empfehlungen_fuer_einen_Indikationskatalog_fuer_den_Notarzteinsatz_NAIK_.pdf']]},
      {title:'Rettungsmittel-Übersicht',text:'RTW, KTW, NEF und weitere Rettungsmittel. Die tatsächliche Vorhaltung und Alarmierung richtet sich nach dem örtlichen Bereichsplan und der AAO.',links:[['SächsLRettDPVO','https://recht.sachsen.de/vorschrift/5617.6']]},
      {title:'Stichwortübersicht Medizin',text:'Im NABS hinterlegte medizinische Stichworte wie ALLERG, CHIR, GYN, INTERN, INTOX, NEURO, PSYCH, REA, TRAUMA, UNKLAR und VERKEHR.',internal:'Die aktive Stichwortlogik wird über den Fragenkatalog und die hinterlegten Regeln erzeugt.'},
      {title:'Besondere Einsatzlagen',text:'MANV, Reanimation, besondere Gefahrenlagen, mehrere Betroffene und Situationen mit zusätzlichem Feuerwehrbedarf.',internal:'Bei besonderen Lagen immer Lageentwicklung, Anzahl Betroffene und Zugangsmöglichkeiten berücksichtigen.'},
      {title:'Kinder-Notfälle',text:'Kinder werden im Fragenbaum separat über Alter/Geburtsdatum und die medizinische Situation berücksichtigt. Bei Kindern gelten besondere Warnzeichen und lokale Handlungsanweisungen.',links:[['ERC Guidelines 2025','https://www.erc.edu/science-research/guidelines/guidelines-2025/']]},
      {title:'Trauma / Blutung / Amputation',text:'Erfassung von Verletzungsmechanismus, Verletzungsmuster, Körperregion, Blutung, Bewusstsein, Atmung und Zugang. Bei Amputationen wird die Verletzungsart differenziert.',internal:'Das Körperschema in NABS ist direkt mit der medizinischen Abfrage verbunden.'},
      {title:'Verbrennungen',text:'Verbrennung, Verbrühung und Verätzung werden im NABS über den Verletzungspfad und das Körperschema erfasst. Ausmaß und relevante Begleitumstände werden getrennt betrachtet.',links:[['ERC Guidelines 2025','https://www.erc.edu/science-research/guidelines/guidelines-2025/']]},
      {title:'Krampfanfall',text:'Erfassung des Anfalls und insbesondere der aktuellen Situation. Für die Disposition ist entscheidend, ob der Anfall anhält/wiederkehrt oder weitere kritische Zeichen bestehen.',links:[['BÄK – NAIK 2023','https://www.bundesaerztekammer.de/fileadmin/user_upload/wissenschaftlicher-beirat/Veroeffentlichungen/Bek_BAEK_Empfehlungen_fuer_einen_Indikationskatalog_fuer_den_Notarzteinsatz_NAIK_.pdf']]},
      {title:'Bewusstlosigkeit',text:'Bewusstlosigkeit bzw. fehlende Ansprechbarkeit ist ein zentrales Warnzeichen. Bei fehlender normaler Atmung springt NABS in den Reanimationspfad.',links:[['ERC Guidelines 2025','https://www.erc.edu/science-research/guidelines/guidelines-2025/']]},
      {title:'Vergiftung / Intoxikation',text:'Bei Vergiftungen möglichst Stoff, Menge, Aufnahmeweg, Zeitpunkt, Verpackung/Behälter und Symptome erfassen. Bei Gefahrstoffbezug zusätzlich die Gefahrgutabfrage verwenden.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]}
    ]
  },
  {
    id:'feuerwehr', icon:'🔥', title:'Feuerwehr',
    items:[
      {title:'Feuerwehr-Stichworte',text:'Aktuell hinterlegte Grundstichworte: B1, B2, B3 sowie TH1–TH3, G1–G3 und SL.',internal:'Die konkrete örtliche AAO kann im Modul QM1 → AAO / Einsatzmittel geändert werden.'},
      {title:'AAO-Übersicht',text:'Grundvorlage aus dem aktuellen NABS-Projekt.',table:[['B1','KLF'],['B2','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['B3','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['G1','HLF'],['G2','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['G3','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['TH1','HLF'],['TH2','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['TH3','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['SL','ELW · KLF · HLF · GW-L · WLF-1 · WLF-2']]},
      {title:'Fahrzeugübersicht',text:'KLF = Kleinlöschfahrzeug · HLF = Hilfeleistungslöschgruppenfahrzeug · ELW = Einsatzleitwagen · GW-L = Gerätewagen Logistik · WLF = Wechselladerfahrzeug. Die konkrete Ausstattung ist örtlich zu pflegen.',internal:'Weitere Fahrzeuge können in der AAO-Verwaltung ergänzt werden.'},
      {title:'B1 / B2 / B3',text:'B1: kleine Lage; B2: mittlere Lage; B3: große/ausgedehnte Lage. Die konkrete Volltextbeschreibung ist in der Einsatzstichwortverwaltung hinterlegt und kann dort geändert werden.'},
      {title:'Technische Hilfeleistung',text:'TH1: u. a. Befreiung Person Aufzug, kleine Wasserschäden, Tierrettung und Absicherung. TH2/TH3 decken größere bzw. personengefährdende technische Lagen ab.',internal:'Die lokale AAO im NABS ist maßgeblich.'},
      {title:'Gefahrgut / ABC',text:'Bei Gefahrgut zuerst Abstand/Eigenschutz beachten, Stoff identifizieren soweit gefahrlos möglich und die Kennzeichnung erfassen. Die NABS-Gefahrgutmaske dokumentiert Gefahrnummer, UN-Nummer, Gefahrzettel, Transport und Menge.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all'],['UNECE ADR 2025','https://unece.org/info/Transport/pub/395786']]},
      {title:'Wasserrettung',text:'Bei Wasser-/Eisunfällen insbesondere Anzahl der Personen, letzte Sichtposition, Strömung/Gefahren, Zugang und sichere Anfahrt erfassen. Eigenschutz und örtliche Wasserrettungsstrukturen beachten.'},
      {title:'Aufzug',text:'NABS führt eine eigene Abfrage für eingeschlossene Personen: Standort, Personenzahl, Dauer, Kabinenposition, Türen, Bewegungs-/Quetschgefahr, weitere Gefahren, Zugang und medizinische Notfälle.',links:[['DGUV – Aufzüge / Notruf','https://www.dguv.de/fb-holzundmetall/sg/sg_smsa/aufzuege/faq/index.jsp']]},
      {title:'Unwetter / Großschaden',text:'Erfassung von Lageumfang, betroffenen Personen, besonderen Gefahren und weiteren wichtigen Informationen. Für größere Lagen kann das Stichwort SL verwendet werden.'}
    ]
  },
  {
    id:'gefahrgut', icon:'☣️', title:'Gefahrgut',
    items:[
      {title:'ADR-Gefahrnummern',text:'Die Gefahrnummer/Kemler-Nummer befindet sich bei vielen Gefahrguttransporten auf der orangefarbenen Tafel. NABS kann die eingegebene Nummer erläutern.',links:[['BAM DGG-Info – Suche nach Gefahrnummer','https://www.dgg.bam.de/dgginfo/search/advanced/all']]},
      {title:'UN-Nummern',text:'UN-Nummern identifizieren gefährliche Stoffe/Gegenstände im Transportrecht. Für belastbare Stoffdaten sollte die BAM-Datenbank verwendet werden; der lokale NABS-Katalog ist nur eine Schnellhilfe.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]},
      {title:'Gefahrzettel',text:'ADR-Gefahrzettel kennzeichnen die Gefahrgutklasse bzw. Unterklasse. NABS zeigt die Klassen 1 bis 9 als auswählbare Symbole.'},
      {title:'GHS-Piktogramme',text:'GHS-Piktogramme gehören zur Einstufung und Kennzeichnung von Chemikalien. Sie sind nicht dasselbe wie ADR-Gefahrzettel. NABS führt beide Systeme getrennt.',links:[['BAuA – Gefahrstoffkennzeichnung','https://www.baua.de/DE/Themen/Chemikalien-Biostoffe/Gefahrstoffe/Einstufung-und-Kennzeichnung/Kennzeichnungselemente/Gefahrenpiktogramme-und-Signalwoerter']]},
      {title:'Kemler-Zahlen',text:'Kemler-/Gefahrnummern geben die wesentliche Gefahr und ggf. zusätzliche Gefahren an. Ein vorangestelltes X kann auf eine gefährliche Reaktion mit Wasser hinweisen.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]},
      {title:'Wichtige Sofortmaßnahmen',text:'Eigenschutz und Abstand zuerst. Keine unnötige Annäherung oder Manipulation unbekannter Stoffe. Stoff/UN/Gefahrnummer nur soweit gefahrlos ablesen. Weitere Maßnahmen nach örtlicher Einsatzführung und den dafür vorgesehenen Einsatzinformationen.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all'],['UNECE ADR 2025','https://unece.org/info/Transport/pub/395786']]}
    ]
  },
  {
    id:'leitstelle', icon:'📞', title:'Leitstelle / Region',
    items:[
      {title:'IRLS Zwickau',text:'Die IRLS Zwickau nimmt den Notruf 112 für den Landkreis Zwickau und Vogtlandkreis entgegen. Die Leitstelle befindet sich bei der Berufsfeuerwehr Zwickau, Crimmitschauer Straße 35, 08056 Zwickau.',links:[['Feuerwehr Zwickau – IRLS Zwickau','https://feuerwehr.zwickau.de/de/leitstelle/05_01-Abteilung-Leitstelle.php'],['Feuerwehr Zwickau – Notruf','https://feuerwehr.zwickau.de/de/leitstelle/notruf.php']]},
      {title:'Wichtige Telefonnummern',text:'112 – Feuerwehr/Rettungsdienst · 116 117 – ärztlicher Bereitschaftsdienst · 0375 19222 – Krankentransport/Anmeldung im Bereich der IRLS Zwickau · Giftnotruf Thüringen 0361 730730.',links:[['Stadt Zwickau – Notdienste','https://www.zwickau.de/de/politik/gesundheit/notdienste.php']]},
      {title:'Sonderrufnummern',text:'Notruf 112 und 110 haben Vorrang bei akuten Notlagen. Weitere regionale Rufnummern sollten vor produktivem Einsatz gegen die aktuelle Leitstellen-/Behördenliste geprüft werden.'},
      {title:'Krankenhäuser',text:'Beispielhafte regionale Zielkliniken mit öffentlich verfügbaren Notaufnahmeinformationen: Pleißental-Klinik Werdau und Klinikum Obergöltzsch Rodewisch. Die konkrete Zielklinik entscheidet der Rettungsdienst nach Lage, Kapazität und Transportziel.',links:[['Pleißental-Klinik – Notaufnahme','https://www.pleissental-klinik.de/fachabteilungen-und-zentren/notaufnahme'],['Klinikum Obergöltzsch Rodewisch – Notaufnahme','https://www.klinikum-obergoeltzsch.de/fachabteilungen/dienste-sonstige-abteilungen/notaufnahme.html']]},
      {title:'Rettungswachen',text:'Im Vogtlandkreis sind u. a. Rettungswachen in Adorf, Auerbach, Elsterberg, Falkenstein, Heinsdorfergrund/Reichenbach, Klingenthal und weiteren Orten dokumentiert. Die offizielle Übersicht des Vogtlandkreises sollte für die aktuelle Standortliste verwendet werden.',links:[['Vogtlandkreis – Notfallmeldestellen / Übersicht','https://www.vogtlandkreis.de/notfallmeldestellen']]},
      {title:'Feuerwachen',text:'Die konkreten örtlichen Feuerwachen und Gerätehäuser sollten über die kommunalen Feuerwehrseiten bzw. die örtliche Datenpflege im NABS aktuell gehalten werden.',links:[['Feuerwehr Zwickau','https://feuerwehr.zwickau.de/']]},
      {title:'Hubschrauberstandorte',text:'Im Leitstellengebiet ist Christoph 46 als regionaler Rettungshubschrauber dokumentiert. Luftrettungsstandorte und Verfügbarkeiten sind dynamisch und sollten deshalb zusätzlich über die aktuelle Leitstellen-/RTH-Datenquelle gepflegt werden.',links:[['Feuerwehr Zwickau – Notruf / Rettungsmittel','https://feuerwehr.zwickau.de/de/leitstelle/notruf.php']]},
      {title:'Besondere Ansprechpartner',text:'IRLS Zwickau: +49 375 19222 für Krankentransport-Anmeldungen; allgemeiner Notruf 112. Für weitere Ansprechpartner sollte eine durch QM1 pflegbare Liste verwendet werden.',links:[['Feuerwehr Zwickau – Leitstelle','https://feuerwehr.zwickau.de/de/leitstelle/05_01-Abteilung-Leitstelle.php']]},
      {title:'Notfallmeldestellen',text:'Bei Ausfall üblicher Kommunikationswege können Notfallmeldestellen aktiviert werden. Im Landkreis Zwickau wurden 120, im Vogtlandkreis 124 Notfallmeldestellen veröffentlicht.',links:[['Landkreis Vogtland – Notfallmeldestellen','https://www.vogtlandkreis.de/notfallmeldestellen'],['Stadt Zwickau – Notfallmeldestellen','https://www.zwickau.de/de/aktuelles/pressemitteilungen/2024/12/s123.php']]}
    ]
  }
];
