export const EHSI_SECTIONS = [
  {
    id:'rettungsdienst', icon:'🚑', title:'Rettungsdienst',
    items:[
      {title:'Notarztindikationen / NEF-Hinweise',text:'Aktuelle fachliche Grundlage für die strukturierte Einschätzung einer möglichen Notarztindikation. Die konkrete Alarmierungsentscheidung bleibt an die örtlichen NAIK-/Leitstellenregeln und die jeweils gültige Dienstanweisung gebunden.',links:[['Bundesärztekammer – NAIK 2023','https://www.bundesaerztekammer.de/fileadmin/user_upload/wissenschaftlicher-beirat/Veroeffentlichungen/Bek_BAEK_Empfehlungen_fuer_einen_Indikationskatalog_fuer_den_Notarzteinsatz_NAIK_.pdf'],['BÄK – Meldung zur Aktualisierung','https://www.bundesaerztekammer.de/presse/aktuelles/detail/bundesaerztekammer-aktualisiert-notarztindikationskatalog']]},
      {title:'Rettungsmittel-Übersicht',text:'RTW, KTW, NEF und weitere Rettungsmittel. Vorhaltung, Standorte und Alarmierung sind anhand des aktuellen Bereichsplans, der örtlichen AAO und der Leitstellenvorgaben zu prüfen.',links:[['SächsLRettDPVO – aktuelle REVOSax-Fassung/Änderungen','https://www.revosax.sachsen.de/vorschrift/21162'],['Rettungszweckverband Südwestsachsen','https://www.rettzv-sws.de/']]},
      {title:'Zwickauer Land / Rettungsdienst Südwestsachsen',text:'Der Rettungszweckverband Südwestsachsen ist Träger des bodengebundenen Rettungsdienstes im Vogtlandkreis und Landkreis Zwickau und betreibt die IRLS Zwickau. Für örtliche Vorhaltung und aktuelle Informationen ist die Verbandsseite die primäre regionale Quelle.',links:[['RettZV Südwestsachsen – aktuell','https://www.rettzv-sws.de/'],['Landkreis Zwickau – Rettungsdienst, Leitstelle und Rettungswachen','https://www.landkreis-zwickau.de/']]},
      {title:'Stichwortübersicht Medizin',text:'Im NABS hinterlegte medizinische Stichworte wie ALLERG, CHIR, GYN, INTERN, INTOX, NEURO, PSYCH, REA, TRAUMA, UNKLAR und VERKEHR. Die tatsächlich aktive Zuordnung wird aus dem Fragenkatalog und den lokalen Regeln erzeugt.',internal:'Bei einer Änderung der lokalen Stichwort-/AAO-Logik muss die aktive NABS-Konfiguration maßgeblich sein.'},
      {title:'Besondere Einsatzlagen',text:'MANV, Reanimation, mehrere Betroffene, besondere Gefahrenlagen und Situationen mit zusätzlichem Feuerwehrbedarf. Anzahl Betroffener, Zugänglichkeit, Lageentwicklung und benötigte Sondermittel sind gesondert zu erfassen.',links:[['SächsBRKG – Großschadensereignisse / Katastrophenschutz','https://revosax.sachsen.de/vorschrift/4911-SaechsBRKG']]},
      {title:'Kinder-Notfälle',text:'Kinder werden im NABS über Alter/Geburtsdatum und die medizinische Situation berücksichtigt. Für Reanimation, ABCDE und spezielle pädiatrische Notfallsituationen stehen aktuelle GRC-Materialien bereit.',links:[['GRC – Reanimationsleitlinien 2025','https://www.grc-org.de/wissenschaft/leitlinien'],['GRC – Leitlinien kompakt 2025','https://www.grc-org.de/files/Contentpages/document/LeitlinienKompakt2025_22.10.2025.pdf']]},
      {title:'Trauma / Blutung / Amputation',text:'Erfassung von Mechanismus, Verletzungsmuster, Blutung, Bewusstsein, Atmung, Körperregion und Zugang. Das NABS-Körperschema ist direkt mit dem medizinischen Abfragepfad verbunden.',links:[['GRC – Reanimationsleitlinien 2025','https://www.grc-org.de/wissenschaft/leitlinien'],['BÄK – NAIK 2023','https://www.bundesaerztekammer.de/fileadmin/user_upload/wissenschaftlicher-beirat/Veroeffentlichungen/Bek_BAEK_Empfehlungen_fuer_einen_Indikationskatalog_fuer_den_Notarzteinsatz_NAIK_.pdf']]},
      {title:'Verbrennungen',text:'Verbrennung, Verbrühung und Verätzung werden über den Verletzungspfad und das Körperschema erfasst. Ausdehnung, Lokalisation, Begleitverletzungen und relevante Atemwegs-/Inhalationszeichen sind getrennt zu berücksichtigen.',links:[['GRC – Reanimationsleitlinien 2025','https://www.grc-org.de/wissenschaft/leitlinien']]},
      {title:'Krampfanfall',text:'Neben dem Auftreten des Anfalls ist die aktuelle Situation entscheidend: anhaltender oder wiederkehrender Anfall, Bewusstsein, Atmung und weitere kritische Zeichen. Die lokale Notarztlogik des NABS ist mit den hinterlegten Regeln abzugleichen.',links:[['BÄK – NAIK 2023','https://www.bundesaerztekammer.de/fileadmin/user_upload/wissenschaftlicher-beirat/Veroeffentlichungen/Bek_BAEK_Empfehlungen_fuer_einen_Indikationskatalog_fuer_den_Notarzteinsatz_NAIK_.pdf']]},
      {title:'Bewusstlosigkeit / Reanimation',text:'Bewusstlosigkeit bzw. fehlende Ansprechbarkeit ist ein zentrales Warnzeichen. Bei fehlender normaler Atmung führt NABS in den Reanimationspfad. Für BLS/ALS und Kinder stehen die GRC-Leitlinien 2025 zur Verfügung.',links:[['GRC – Leitlinien 2025','https://www.grc-org.de/wissenschaft/leitlinien'],['GRC – Leitlinien kompakt 2025','https://www.grc-org.de/files/Contentpages/document/LeitlinienKompakt2025_22.10.2025.pdf']]},
      {title:'Vergiftung / Intoxikation',text:'Wenn möglich Stoff, Menge, Aufnahmeweg, Zeitpunkt, Behälter/Verpackung und Symptome erfassen. Bei Gefahrstoffbezug zusätzlich die NABS-Gefahrgutabfrage und die BAM-Datenbank verwenden.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]},
      {title:'Psychiatrische Notfälle',text:'Psychische Ausnahmesituationen werden im NABS über den PSYCH-Pfad erfasst. Für Hilfen und Schutzmaßnahmen bei psychischen Erkrankungen gilt in Sachsen das aktuelle SächsPsychKHG.',links:[['REVOSax – SächsPsychKHG','https://www.revosax.sachsen.de/vorschrift/20964']]},
      {title:'Schwangerschaft / Geburt',text:'Für schwangerschaftsbezogene Fragestellungen sind neben medizinischen Leitlinien die einschlägigen sächsischen Rechtsgrundlagen zu berücksichtigen. Das einschlägige Landesgesetz heißt SächsSchKGAG (Ausführungsgesetz zum Schwangerschaftskonfliktgesetz).',links:[['REVOSax – SächsSchKGAG','https://www.revosax.sachsen.de/vorschrift/10180-SaechsSchKGAG']]},
      {title:'Reanimation / aktuelle Handlungsanweisungen',text:'Die GRC-Reanimationsleitlinien 2025 sind die aktuelle deutsche Leitlinienbasis für Wiederbelebungsmaßnahmen. Die GRC veröffentlicht dazu zusätzlich kompakte Leitlinien und Poster für Erwachsene, Kinder und spezielle Situationen.',links:[['GRC – Leitlinien 2025','https://www.grc-org.de/wissenschaft/leitlinien'],['GRC – Infomaterialien und Poster','https://www.grc-org.de/medien/infomaterialien-downloads']]}
    ]
  },
  {
    id:'feuerwehr', icon:'🔥', title:'Feuerwehr',
    items:[
      {title:'Feuerwehr-Stichworte',text:'Aktuell hinterlegte Grundstichworte: B1, B2, B3 sowie TH1–TH3, G1–G3 und SL. Die konkrete Alarmierung ist an die örtliche AAO gekoppelt.',internal:'Die konkrete örtliche AAO kann im Modul QM1 → AAO / Einsatzmittel gepflegt werden.',links:[['REVOSax – SächsBRKG','https://revosax.sachsen.de/vorschrift/4911-SaechsBRKG']]},
      {title:'AAO-Übersicht',text:'Grundvorlage aus dem aktuellen NABS-Projekt.',table:[['B1','KLF'],['B2','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['B3','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['G1','HLF'],['G2','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['G3','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['TH1','HLF'],['TH2','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['TH3','ELW · KLF · HLF · GW-L · WLF-2 · WLF-1'],['SL','ELW · KLF · HLF · GW-L · WLF-1 · WLF-2']]},
      {title:'Fahrzeugübersicht',text:'KLF = Kleinlöschfahrzeug · HLF = Hilfeleistungslöschgruppenfahrzeug · ELW = Einsatzleitwagen · GW-L = Gerätewagen Logistik · WLF = Wechselladerfahrzeug. Die konkrete Ausstattung ist örtlich zu pflegen.',internal:'Weitere Fahrzeuge können in der AAO-Verwaltung ergänzt werden.'},
      {title:'B1 / B2 / B3',text:'B1: kleine Lage; B2: mittlere Lage; B3: große/ausgedehnte Lage. Die konkrete Volltextbeschreibung ist in der Einsatzstichwortverwaltung hinterlegt und kann dort geändert werden.'},
      {title:'Technische Hilfeleistung',text:'TH1: u. a. Befreiung Person Aufzug, kleine Wasserschäden, Tierrettung und Absicherung. TH2/TH3 decken größere bzw. personengefährdende technische Lagen ab.',internal:'Die lokale AAO im NABS ist maßgeblich.'},
      {title:'Gefahrgut / ABC',text:'Bei Gefahrgut zuerst Abstand/Eigenschutz beachten, Stoff identifizieren soweit gefahrlos möglich und die Kennzeichnung erfassen. Die NABS-Gefahrgutmaske dokumentiert Gefahrnummer, UN-Nummer, Gefahrzettel, Transport und Menge.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all'],['UNECE ADR – offizielle Publikationen','https://unece.org/info/Transport/pub/395786']]},
      {title:'Wasserrettung',text:'Bei Wasser-/Eisunfällen Anzahl der Personen, letzte Sichtposition, Strömung/Gefahren, Zugang und sichere Anfahrt erfassen. Eigenschutz und örtliche Wasserrettungsstrukturen beachten.',links:[['SächsBRKG – Katastrophenschutz / Gefahrenabwehr','https://revosax.sachsen.de/vorschrift/4911-SaechsBRKG']]},
      {title:'Aufzug',text:'NABS führt eine eigene Abfrage für eingeschlossene Personen: Standort, Personenzahl, Dauer, Kabinenposition, Türen, Bewegungs-/Quetschgefahr, weitere Gefahren, Zugang und medizinische Notfälle.',links:[['DGUV – Aufzüge / Notruf','https://www.dguv.de/fb-holzundmetall/sg/sg_smsa/aufzuege/faq/index.jsp']]},
      {title:'Unwetter / Großschaden',text:'Erfassung von Lageumfang, betroffenen Personen, besonderen Gefahren und weiteren wichtigen Informationen. Für größere Lagen kann das Stichwort SL verwendet werden.',links:[['REVOSax – SächsBRKG','https://revosax.sachsen.de/vorschrift/4911-SaechsBRKG']]},
      {title:'Rechtsgrundlagen Feuerwehr / Katastrophenschutz',text:'Für Aufgaben, Zuständigkeiten und Leitstellenorganisation ist das aktuelle SächsBRKG die zentrale Landesrechtsquelle. REVOSax stellt die jeweils veröffentlichte Landesrechtsfassung bereit.',links:[['REVOSax – SächsBRKG','https://revosax.sachsen.de/vorschrift/4911-SaechsBRKG'],['REVOSax – Landesrecht Sachsen','https://www.revosax.sachsen.de/']]}
    ]
  },
  {
    id:'gefahrgut', icon:'☣️', title:'Gefahrgut',
    items:[
      {title:'ADR-Gefahrnummern',text:'Die Gefahrnummer/Kemler-Nummer befindet sich bei vielen Gefahrguttransporten auf der orangefarbenen Tafel. NABS kann die eingegebene Nummer als Schnellhilfe erläutern.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all'],['UNECE ADR – offizielle Publikationen','https://unece.org/info/Transport/pub/395786']]},
      {title:'UN-Nummern',text:'UN-Nummern identifizieren gefährliche Stoffe/Gegenstände im Transportrecht. Für belastbare Stoffdaten sollte die BAM-Datenbank verwendet werden; der lokale NABS-Katalog ist nur eine Schnellhilfe.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]},
      {title:'Gefahrzettel / ADR-Klassen',text:'ADR-Gefahrzettel kennzeichnen die Gefahrgutklasse bzw. Unterklasse. NABS zeigt die Klassen 1 bis 9 als auswählbare Symbole.'},
      {title:'GHS-Piktogramme',text:'GHS-Piktogramme gehören zur Einstufung und Kennzeichnung von Chemikalien. Sie sind nicht dasselbe wie ADR-Gefahrzettel. NABS führt beide Systeme getrennt.',links:[['BAuA – Gefahrenpiktogramme und Signalwörter','https://www.baua.de/DE/Themen/Chemikalien-Biostoffe/Gefahrstoffe/Einstufung-und-Kennzeichnung/Kennzeichnungselemente/Gefahrenpiktogramme-und-Signalwoerter']]},
      {title:'Kemler-Zahlen',text:'Kemler-/Gefahrnummern geben die wesentliche Gefahr und ggf. zusätzliche Gefahren an. Ein vorangestelltes X weist auf eine gefährliche Reaktion mit Wasser hin.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]},
      {title:'Wichtige Sofortmaßnahmen',text:'Eigenschutz und Abstand zuerst. Keine unnötige Annäherung oder Manipulation unbekannter Stoffe. Stoff/UN/Gefahrnummer nur soweit gefahrlos ablesen. Weitere Maßnahmen nach örtlicher Einsatzführung und vorgesehenen Einsatzinformationen.',links:[['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all'],['UNECE ADR – offizielle Publikationen','https://unece.org/info/Transport/pub/395786']]},
      {title:'Aktuelle Rechts-/Informationsquellen',text:'Für Gefahrgutrecht und Stoffinformationen sollten die aktuellen offiziellen Veröffentlichungen von UNECE und BAM genutzt werden. Lokale NABS-Schnellhilfen ersetzen keine aktuelle Gefahrgutdatenbank oder Einsatzanweisung.',links:[['UNECE Transport – ADR 2025','https://unece.org/info/Transport/pub/395786'],['BAM DGG-Info','https://www.dgg.bam.de/dgginfo/search/advanced/all']]}
    ]
  },
  {
    id:'leitstelle', icon:'📞', title:'Leitstelle / Region',
    items:[
      {title:'IRLS Zwickau / RettZV Südwestsachsen',text:'Der RettZV Südwestsachsen ist Träger des bodengebundenen Rettungsdienstes in Vogtlandkreis und Landkreis Zwickau und der IRLS Zwickau. Für aktuelle Informationen und Kontaktdaten ist die Verbandsseite maßgeblich.',links:[['RettZV Südwestsachsen – aktuell','https://www.rettzv-sws.de/'],['Feuerwehr Zwickau – IRLS','https://feuerwehr.zwickau.de/de/leitstelle/05_01-Abteilung-Leitstelle.php']]},
      {title:'Wichtige Telefonnummern',text:'112 – Feuerwehr/Rettungsdienst · 110 – Polizei · 116117 – ärztlicher Bereitschaftsdienst · 0375 19222 – Krankentransport/Anmeldung im Bereich der IRLS Zwickau. Nummern vor Verwendung gegen die aktuelle regionale Quelle prüfen.',links:[['Landkreis Zwickau – Notsituationen und Vergiftungen','https://www.landkreis-zwickau.de/notsituationen-und-vergiftungen']]},
      {title:'Sonderrufnummern',text:'Notruf 112 und 110 haben Vorrang bei akuten Notlagen. Weitere regionale Rufnummern sollten über aktuelle Behörden-/Leitstellenquellen gepflegt werden.',links:[['Landkreis Zwickau – Notsituationen und Vergiftungen','https://www.landkreis-zwickau.de/notsituationen-und-vergiftungen']]},
      {title:'Krankenhäuser / Zielkliniken',text:'Regionale Zielkliniken und Notaufnahmen sollten über aktuelle Klinikseiten gepflegt werden. Die konkrete Zielklinik richtet sich nach Lage, Transportfähigkeit, Indikation und den örtlichen Vorgaben.',links:[['Landkreis Zwickau – Gesundheitsinformationen','https://www.landkreis-zwickau.de/'],['RettZV Südwestsachsen','https://www.rettzv-sws.de/']]},
      {title:'Rettungswachen / Zwickauer Land',text:'Für aktuelle Rettungswachen, Rettungsmittel und Vorhaltung sollte die Quelle des RettZV Südwestsachsen bzw. der zuständige Bereichsplan verwendet werden.',links:[['RettZV Südwestsachsen','https://www.rettzv-sws.de/'],['Landkreis Zwickau','https://www.landkreis-zwickau.de/']]},
      {title:'Feuerwachen',text:'Die örtlichen Feuerwachen und Gerätehäuser sind kommunal zu pflegen. Für Zwickau ist die Feuerwehr Zwickau die aktuelle Primärquelle.',links:[['Feuerwehr Zwickau','https://feuerwehr.zwickau.de/']]},
      {title:'Hubschrauberstandorte / Luftrettung',text:'Luftrettungsstandorte und Verfügbarkeiten können sich ändern. Deshalb sollten RTH-Informationen über aktuelle Leitstellen-/Rettungsdienstquellen gepflegt werden.',links:[['RettZV Südwestsachsen','https://www.rettzv-sws.de/'],['Feuerwehr Zwickau – Leitstelle','https://feuerwehr.zwickau.de/de/leitstelle/05_01-Abteilung-Leitstelle.php']]},
      {title:'Besondere Ansprechpartner',text:'Ansprechpartner für Rettungsdienst, Brandschutz, Katastrophenschutz und Behörden sollen über die aktuellen Behördenquellen gepflegt werden.',links:[['Landkreis Zwickau – Brandschutz/Rettungsdienst/Katastrophenschutz','https://www.landkreis-zwickau.de/detail?id=4251&type=VB'],['RettZV Südwestsachsen','https://www.rettzv-sws.de/']]},
      {title:'Notfallmeldestellen',text:'Für länger andauernde Ausfälle von Mobilfunk, Festnetz oder Internet stehen regionale Notfallmeldestellen zur Verfügung. Die aktuellen Standorte müssen über Landkreis/Stadt gepflegt werden.',links:[['Stadt Zwickau – Notfallmeldestellen','https://www.zwickau.de/de/aktuelles/pressemitteilungen/2024/12/521.php']]},
      {title:'REVOSax – zentrale Landesrechtsquelle',text:'REVOSax ist die zentrale Such- und Informationsplattform für das Landesrecht Sachsen. Von hier aus sollten bei Rechtsänderungen die aktuellen Fassungen geprüft werden.',links:[['REVOSax – Landesrecht Sachsen','https://www.revosax.sachsen.de/']]}
    ]
  },
  {
    id:'tiere', icon:'🐝', title:'Tiere / Natur & Zuständigkeiten',
    items:[
      {title:'Bienen, Wespen und Hornissen',text:'Bei einem Nest nicht eigenständig eingreifen. Besonders geschützte Arten wie Hornissen unterliegen artenschutzrechtlichen Vorgaben. Im Landkreis Zwickau ist die Naturschutzbehörde für Artenschutzvollzug und Hornissen zuständig; bei akuter Gefahr ist zunächst die Einsatzlage/Eigenschutz zu bewerten.',links:[['Landkreis Zwickau – Hornissen / Nestbeseitigung','https://www.landkreis-zwickau.de/detail?id=3001&type=VB'],['Landkreis Zwickau – Zuständigkeiten Artenschutz (PDF)','https://www.landkreis-zwickau.de/uploads/formulare/ZustaendigkeitenArtenschutz_3721.pdf']]},
      {title:'Artenschutz / Naturschutz – Zwickau und Mosel',text:'Für den Ortsteil Mosel der Stadt Zwickau ist der Landkreis Zwickau als zuständige untere Naturschutzbehörde für die dort genannten Artenschutzangelegenheiten die relevante Kreisbehörde. Die konkrete Zuständigkeit ist im Einzelfall über die aktuelle Behördenliste zu prüfen.',links:[['Landkreis Zwickau – Naturschutz, Land- und Forstwirtschaft','https://www.landkreis-zwickau.de/detail?id=154&type=BHW'],['Landkreis Zwickau – Artenschutz-Zuständigkeiten','https://www.landkreis-zwickau.de/uploads/formulare/ZustaendigkeitenArtenschutz_3721.pdf']]},
      {title:'Jäger / Jagdbehörde',text:'Die untere Jagdbehörde des Landkreises Zwickau ist für zahlreiche jagdrechtliche Aufgaben zuständig, darunter Jagdbezirke, Jagderlaubnisse, Jägerprüfungen, Jagdschutz und Wildseuchen. Für akute Wildlagen ist zusätzlich der konkrete Jagdausübungsberechtigte bzw. örtliche Ansprechpartner zu berücksichtigen.',links:[['Landkreis Zwickau – Jagdbehörde','https://www.landkreis-zwickau.de/detail?id=2531&type=VB'],['REVOSax – Sächsisches Jagdgesetz','https://revosax.sachsen.de/vorschrift/12495'],['Sachsenforst – Jagdbehörden','https://www.wald.sachsen.de/jagdbehoerden-4580.html']]},
      {title:'Veterinäramt – Landkreis Zwickau / Mosel',text:'Das Lebensmittelüberwachungs- und Veterinäramt (LÜVA) des Landkreises Zwickau bearbeitet u. a. Tierschutz, Tierseuchen und Tiergesundheitsschutz. Für Zwickau/Mosel ist bei veterinärrechtlichen Zuständigkeiten die aktuelle Kreisbehörde die zentrale Quelle.',links:[['Landkreis Zwickau – Lebensmittelüberwachungs- und Veterinäramt','https://www.landkreis-zwickau.de/detail?id=47&type=BHW'],['Landkreis Zwickau – Tierschutz / Tierarzneimittel / Fleischhygiene','https://www.landkreis-zwickau.de/detail?id=117&type=VB'],['Landkreis Zwickau – Tierseuchen / Tiergesundheitsschutz','https://www.landkreis-zwickau.de/detail?id=149&type=BHW']]},
      {title:'Tierschutz / Tierquälerei',text:'Tierschutzrechtliche Verstöße werden vom LÜVA des Landkreises Zwickau bearbeitet. Bei unmittelbarer Gefahr für Menschen oder Tiere ist die Lage zunächst über die zuständigen Einsatzkräfte abzusichern.',links:[['Landkreis Zwickau – Tierschutzrechtliche Verstöße','https://www.landkreis-zwickau.de/tierschutzrechtliche-verstosse'],['Landkreis Zwickau – Tierschutz / Veterinäramt','https://www.landkreis-zwickau.de/detail?id=117&type=VB']]},
      {title:'Wildtier / verendetes Wild / ASP',text:'Bei verendet aufgefundenen oder krank erlegten Wildschweinen bestehen im Landkreis Zwickau Melde- und Mitwirkungspflichten im Zusammenhang mit der Afrikanischen Schweinepest. Die aktuelle Verfahrensinformation des LÜVA ist zu verwenden.',links:[['Landkreis Zwickau – ASP / Wildschweine','https://www.landkreis-zwickau.de/detail?id=5301&type=VB'],['Aktuelle Trichinenuntersuchung / LÜVA','https://www.landkreis-zwickau.de/uploads/formulare/20260201VeroeffentlichungTUSLKZ_3451.pdf']]},
      {title:'Merksatz für die Leitstelle',text:'Nicht jede Tier- oder Insektenlage ist eine Feuerwehrlage. Zuständigkeit, unmittelbare Gefahr, Artenschutz, Tierseuchen-/Tierschutzbezug und erforderliche Gefahrenabwehr getrennt bewerten. Die Behördenlinks in diesem Bereich sind als aktuelle Nachschlagequellen vorgesehen.'}
    ]
  }
];
