// Gefahrgut-Hilfsdaten NABS V68.46
// Kemler/HIN meanings follow ADR 2025 section 5.3.2.3.2.
export const KEMLER_MEANINGS = {
  '20':'reaktionsträges/erstickendes Gas oder Gas ohne Zusatzgefahr','22':'tiefgekühlt verflüssigtes Gas, erstickend','223':'tiefgekühlt verflüssigtes Gas, brennbar','225':'tiefgekühlt verflüssigtes Gas, brandfördernd','23':'brennbares Gas','236':'brennbares Gas, giftig','239':'brennbares Gas, kann spontan zu heftiger Reaktion führen','25':'brandförderndes Gas','26':'giftiges Gas','265':'giftiges Gas, brandfördernd','268':'giftiges Gas, ätzend','28':'ätzendes Gas',
  '30':'entzündbarer flüssiger Stoff (Flammpunkt 23–61 °C) oder selbsterhitzungsfähiger flüssiger Stoff','323':'entzündbarer flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet','X323':'entzündbarer flüssiger Stoff, der mit Wasser gefährlich reagiert und entzündbare Gase bildet','33':'leicht entzündbarer flüssiger Stoff (Flammpunkt unter 23 °C)','333':'selbstentzündlicher (pyrophorer) flüssiger Stoff','X333':'selbstentzündlicher (pyrophorer) flüssiger Stoff, der mit Wasser gefährlich reagiert','336':'leicht entzündbarer flüssiger Stoff, giftig','338':'leicht entzündbarer flüssiger Stoff, ätzend','X338':'leicht entzündbarer flüssiger Stoff, ätzend, der mit Wasser gefährlich reagiert','339':'leicht entzündbarer flüssiger Stoff, der spontan zu heftiger Reaktion führen kann','36':'entzündbarer flüssiger Stoff, schwach giftig, oder selbsterhitzungsfähiger flüssiger Stoff, giftig','362':'entzündbarer flüssiger Stoff, giftig, der mit Wasser reagiert und entzündbare Gase bildet','368':'entzündbarer flüssiger Stoff, giftig, ätzend','38':'entzündbarer flüssiger Stoff, schwach ätzend, oder selbsterhitzungsfähiger flüssiger Stoff, ätzend','382':'entzündbarer flüssiger Stoff, ätzend, der mit Wasser reagiert und entzündbare Gase bildet','39':'entzündbarer flüssiger Stoff, der spontan zu heftiger Reaktion führen kann',
  '40':'entzündbarer oder selbsterhitzungsfähiger fester Stoff','423':'fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet','X423':'entzündbarer fester Stoff, der mit Wasser gefährlich reagiert und entzündbare Gase bildet','43':'selbstentzündlicher (pyrophorer) fester Stoff','44':'entzündbarer fester Stoff in geschmolzenem Zustand bei erhöhter Temperatur','446':'entzündbarer fester Stoff, giftig, in geschmolzenem Zustand bei erhöhter Temperatur','46':'entzündbarer oder selbsterhitzungsfähiger fester Stoff, giftig','462':'giftiger fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet','X462':'fester Stoff, der mit Wasser gefährlich reagiert und giftige Gase bildet','48':'entzündbarer oder selbsterhitzungsfähiger fester Stoff, ätzend','482':'ätzender fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet','X482':'fester Stoff, der mit Wasser gefährlich reagiert und ätzende Gase bildet',
  '50':'brandfördernder (oxidierender) Stoff','539':'entzündbares organisches Peroxid','55':'stark brandfördernder Stoff','556':'stark brandfördernder Stoff, giftig','558':'stark brandfördernder Stoff, ätzend','559':'stark brandfördernder Stoff, der spontan zu heftiger Reaktion führen kann','56':'brandfördernder Stoff, giftig','568':'brandfördernder Stoff, giftig, ätzend','58':'brandfördernder Stoff, ätzend','59':'brandfördernder Stoff, der spontan zu heftiger Reaktion führen kann',
  '60':'giftiger oder schwach giftiger Stoff','606':'ansteckungsgefährlicher Stoff','623':'giftiger flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet','63':'giftiger Stoff, entzündbar (Flammpunkt 23–61 °C)','638':'giftiger Stoff, entzündbar (Flammpunkt 23–61 °C), ätzend','639':'giftiger Stoff, entzündbar, der spontan zu heftiger Reaktion führen kann','64':'giftiger fester Stoff, entzündbar oder selbsterhitzungsfähig','642':'giftiger fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet','65':'giftiger Stoff, brandfördernd','66':'sehr giftiger Stoff','663':'sehr giftiger Stoff, entzündbar (Flammpunkt nicht über 61 °C)','664':'sehr giftiger fester Stoff, entzündbar oder selbsterhitzungsfähig','665':'sehr giftiger Stoff, brandfördernd','668':'sehr giftiger Stoff, ätzend','669':'sehr giftiger Stoff, der spontan zu heftiger Reaktion führen kann',
  '68':'giftiger Stoff, ätzend','69':'giftiger oder schwach giftiger Stoff, der spontan zu heftiger Reaktion führen kann','70':'radioaktiver Stoff','75':'radioaktiver Stoff, brandfördernd','768':'radioaktiver Stoff, giftig, ätzend','77':'hochradioaktiver Stoff','78':'radioaktiver Stoff, ätzend','80':'ätzender oder schwach ätzender Stoff','X80':'ätzender oder schwach ätzender Stoff, der mit Wasser gefährlich reagiert','823':'ätzender flüssiger Stoff, der mit Wasser reagiert und entzündbare Gase bildet','83':'ätzender oder schwach ätzender Stoff, entzündbar (Flammpunkt 23–61 °C)','X83':'ätzender Stoff, entzündbar, der mit Wasser gefährlich reagiert','836':'ätzender Stoff, entzündbar (Flammpunkt 23–61 °C), giftig','839':'ätzender Stoff, entzündbar, der spontan zu heftiger Reaktion führen kann','X839':'ätzender Stoff, entzündbar, spontan reaktionsfähig, reagiert gefährlich mit Wasser','84':'ätzender fester Stoff, entzündbar oder selbsterhitzungsfähig','842':'ätzender fester Stoff, der mit Wasser reagiert und entzündbare Gase bildet','85':'ätzender oder schwach ätzender Stoff, brandfördernd','856':'ätzender Stoff, brandfördernd und giftig','86':'ätzender oder schwach ätzender Stoff, giftig','88':'stark ätzender Stoff','X88':'stark ätzender Stoff, der mit Wasser gefährlich reagiert','883':'stark ätzender Stoff, entzündbar (Flammpunkt 23–61 °C)','884':'stark ätzender fester Stoff, entzündbar oder selbsterhitzungsfähig','885':'stark ätzender Stoff, brandfördernd','886':'stark ätzender Stoff, giftig','X886':'stark ätzender Stoff, giftig, der mit Wasser gefährlich reagiert','89':'ätzender oder schwach ätzender Stoff, der spontan zu heftiger Reaktion führen kann','90':'umweltgefährdender Stoff oder verschiedene gefährliche Stoffe','99':'verschiedene gefährliche Stoffe in erwärmtem Zustand'
};

// Häufige/typische UN-Nummern für die Einsatzabfrage. Für rechtsverbindliche
// ADR-Entscheidungen muss immer die aktuelle ADR/BAM-Stoffliste geprüft werden.
export const UN_DANGEROUS_GOODS = {
 '1005':{name:'Ammoniak, wasserfrei',class:'2.3',hin:'268'},'1013':{name:'Kohlendioxid',class:'2.2',hin:'20'},'1017':{name:'Chlor',class:'2.3',hin:'268'},'1049':{name:'Wasserstoff, verdichtet',class:'2.1',hin:'23'},'1072':{name:'Sauerstoff, verdichtet',class:'2.2',hin:'25'},'1075':{name:'Flüssiggase (z. B. Propan/Butan), Gemisch',class:'2.1',hin:'23'},
 '1090':{name:'Aceton',class:'3',hin:'33'},'1114':{name:'Benzol',class:'3',hin:'33'},'1133':{name:'Klebstoffe mit entzündbarem flüssigem Stoff',class:'3',hin:'33'},'1170':{name:'Ethanol (Ethylalkohol) oder Ethanol, Lösung',class:'3',hin:'33 / 30'},'1173':{name:'Ethylacetat',class:'3',hin:'33'},'1193':{name:'Ethylmethylketon (Methylethylketon)',class:'3',hin:'33'},'1202':{name:'Dieselkraftstoff / Gasöl / Heizöl, leicht',class:'3',hin:'30'},'1203':{name:'Benzin / Ottokraftstoff',class:'3',hin:'33'},'1223':{name:'Kerosin',class:'3',hin:'30'},'1230':{name:'Methanol',class:'3',hin:'336'},'1233':{name:'Methylamylacetat',class:'3',hin:'30'},'1263':{name:'Farbe / Lack / verwandte Stoffe',class:'3',hin:'33'},'1267':{name:'Rohöl',class:'3',hin:'33'},'1268':{name:'Erdöldestillate, n.a.g.',class:'3',hin:'33'},'1789':{name:'Salzsäure',class:'8',hin:'80'},'1824':{name:'Natriumhydroxidlösung',class:'8',hin:'80'},'1830':{name:'Schwefelsäure',class:'8',hin:'80'},'1832':{name:'Schwefelsäure, verbraucht',class:'8',hin:'80'},'2023':{name:'Epichlorhydrin',class:'6.1',hin:'63'},'2031':{name:'Salpetersäure',class:'8 / 5.1',hin:'80 / 85'},'2073':{name:'Ammoniaklösung',class:'2.2',hin:'80'},'2209':{name:'Formaldehydlösung',class:'8',hin:'80'},'2794':{name:'Batterien, nass, mit Säure gefüllt',class:'8',hin:'80'},'2796':{name:'Schwefelsäure, Batterieflüssigkeit',class:'8',hin:'80'},'2800':{name:'Batterien, nass, mit Alkalielektrolyt',class:'8',hin:'80'},'3082':{name:'Umweltgefährdender Stoff, flüssig, n.a.g.',class:'9',hin:'90'},'3077':{name:'Umweltgefährdender Stoff, fest, n.a.g.',class:'9',hin:'90'},'3166':{name:'Fahrzeug, mit entzündbarem flüssigem Kraftstoff',class:'9',hin:''},'3480':{name:'Lithium-Ionen-Batterien',class:'9',hin:''},'3481':{name:'Lithium-Ionen-Batterien in Ausrüstung / mit Ausrüstung',class:'9',hin:''},'3536':{name:'Lithiumbatterien in Ladungsträger',class:'9',hin:''},'3551':{name:'Natrium-Ionen-Batterien',class:'9',hin:''},'3556':{name:'Fahrzeug, mit Lithium-Ionen-Batterie betrieben',class:'9',hin:''},'3557':{name:'Fahrzeug, mit Lithium-Metall-Batterie betrieben',class:'9',hin:''},'3558':{name:'Fahrzeug, mit Natrium-Ionen-Batterie betrieben',class:'9',hin:''}
};

export const GHS_SYMBOLS=[
 ['GHS01','Explosiv'],['GHS02','Entzündbar'],['GHS03','Brandfördernd'],['GHS04','Gas unter Druck'],['GHS05','Ätzend'],['GHS06','Akut giftig'],['GHS07','Reizend / gesundheitsschädlich'],['GHS08','Gesundheitsgefahr'],['GHS09','Umweltgefährlich']
];

export const ADR_LABELS=[
 ['ADR1','1','Explosive Stoffe / Gegenstände','explosive','💥'],
 ['ADR1_4','1.4','Explosive Stoffe / Gegenstände, geringe Explosionsgefahr','explosive','💥'],
 ['ADR1_5','1.5','Sehr empfindliche explosive Stoffe','explosive','💥'],
 ['ADR1_6','1.6','Extrem unempfindliche explosive Gegenstände','explosive','💥'],
 ['ADR2_1','2.1','Entzündbare Gase','gas-flammable','🔥'],
 ['ADR2_2','2.2','Nicht entzündbare, nicht giftige Gase','gas','▬'],
 ['ADR2_3','2.3','Giftige Gase','gas-toxic','☠'],
 ['ADR3','3','Entzündbare flüssige Stoffe','flammable','🔥'],
 ['ADR4_1','4.1','Entzündbare feste Stoffe','solid-flammable','🔥'],
 ['ADR4_2','4.2','Selbstentzündliche Stoffe','self-heating','🔥'],
 ['ADR4_3','4.3','Stoffe, die mit Wasser entzündbare Gase bilden','water-reactive','💧'],
 ['ADR5_1','5.1','Entzündend (oxidierend) wirkende Stoffe','oxidizing','⭕'],
 ['ADR5_2','5.2','Organische Peroxide','organic-peroxide','🔥'],
 ['ADR6_1','6.1','Giftige Stoffe','toxic','☠'],
 ['ADR6_2','6.2','Ansteckungsgefährliche Stoffe','infectious','☣'],
 ['ADR7','7','Radioaktive Stoffe','radioactive','☢'],
 ['ADR8','8','Ätzende Stoffe','corrosive','🧪'],
 ['ADR9','9','Verschiedene gefährliche Stoffe und Gegenstände','misc','▥'],
 ['ADR9A','9A','Lithium-/Natrium-Ionen-Batterien','battery','▥']
];

export const TRANSPORT_TYPES=['PKW','LKW','Sattelzug / Tankauflieger','Tankfahrzeug','Gefahrgut-LKW','Bus','Motorrad','Fahrrad','Lieferwagen / Transporter','Bahn / Güterzug','Container / Wechselbrücke','Tankcontainer','Anhänger','Arbeitsmaschine','Sonstiges'];
