import { authState, logout, read, write } from './firebase-rest.js?v=20260920v60';
const $=id=>document.getElementById(id);
const ADMIN='SrRHH7RgmDRXOCKcHy2mOQANrTk1';
const TYPES={
  pruefung:{path:'qm_pruefungen',title:'Qualitätsprüfung',fields:[['titel','Titel','text','full'],['bereich','Bereich','select',''],['faellig','Fällig am','date',''],['status','Status','select',['offen','pruefung','erledigt']],['pruefpunkte','Prüfpunkte / Umfang','textarea','full'],['bemerkung','Bemerkung','textarea','full']]},
  abweichung:{path:'qm_abweichungen',title:'Qualitätsabweichung',fields:[['titel','Bezeichnung','text','full'],['bereich','Bereich','select',''],['art','Art','select',['Inhalt','Technik','Quelle','Regionaldaten','Bedienung','Sonstiges']],['prioritaet','Priorität','select',['Niedrig','Mittel','Hoch']],['beschreibung','Beschreibung','textarea','full'],['ursache','Vermutete Ursache','textarea','full'],['massnahme','Vorgesehene Maßnahme','textarea','full'],['status','Status','select',['neu','pruefung','massnahme','erledigt']]]},
  massnahme:{path:'qm_massnahmen',title:'Korrekturmaßnahme',fields:[['titel','Maßnahme','text','full'],['bezug','Bezug / Abweichung','text',''],['verantwortlich','Verantwortlich','text',''],['frist','Frist','date',''],['status','Status','select',['neu','bearbeitung','umsetzung','kontrolle','erledigt']],['beschreibung','Beschreibung','textarea','full'],['wirksamkeit','Wirksamkeitskontrolle','textarea','full']]},
  aenderung:{path:'qm_aenderungen',title:'Änderung dokumentieren',fields:[['titel','Was wurde geändert?','text','full'],['bereich','Bereich','select',''],['datum','Änderungsdatum','date',''],['grund','Warum wurde geändert?','textarea','full'],['auswirkung','Auswirkung / betroffene Bereiche','textarea','full'],['status','Freigabestatus','select',['entwurf','pruefung','freigegeben']],['freigegebenAm','Freigegeben am','date','']]},
  quellenpruefung:{path:'qm_quellenpruefungen',title:'Quellenprüfung',fields:[['titel','Quelle / Dokument','text','full'],['bereich','Bereich','select',''],['geprueftAm','Geprüft am','date',''],['naechstePruefung','Nächste Prüfung','date',''],['status','Status','select',['offen','geprueft','ueberfaellig']],['bemerkung','Prüfbemerkung','textarea','full']]},
  schulung:{path:'qm_schulungen',title:'Schulung / Unterweisung',fields:[['titel','Schulung','text','full'],['bereich','Bereich','select',''],['datum','Datum','date',''],['teilnehmer','Teilnehmer / Zielgruppe','text',''],['status','Status','select',['geplant','durchgefuehrt','ausgewertet']],['inhalt','Inhalt / Unterweisung','textarea','full']]},
  dokument:{path:'qm_dokumente',title:'QM-Dokument',fields:[['titel','Bezeichnung','text','full'],['art','Dokumentart','select',['QM-Handbuch','Verfahrensanweisung','Arbeitsanweisung','Prüfliste','Schulung','Sonstiges']],['version','Version','text',''],['datum','Stand','date',''],['status','Status','select',['entwurf','freigegeben','archiv']],['link','Link / Speicherort','text','full'],['bemerkung','Bemerkung','textarea','full']]}
};
const areas=[['medizin','🚑 Rettungsdienst / Medizin'],['brand','🔥 Feuerwehr / Brand'],['thl','🛠️ Technische Hilfeleistung'],['abc','☣️ Gefahrgut / ABC'],['leitstelle','📞 Leitstelle / Region'],['tiere','🐝 Tiere / Natur & Zuständigkeiten']];
let data={};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function areaOptions(){return areas.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');}
function statusText(s){return ({offen:'Offen',pruefung:'In Prüfung',erledigt:'Erledigt',neu:'Neu',massnahme:'Maßnahme',bearbeitung:'In Bearbeitung',umsetzung:'Umsetzung',kontrolle:'Kontrolle',entwurf:'Entwurf',freigegeben:'Freigegeben',geprueft:'Geprüft',ueberfaellig:'Überfällig',geplant:'Geplant',durchgefuehrt:'Durchgeführt',ausgewertet:'Ausgewertet',archiv:'Archiv'})[s]||s||'—'}
function renderItem(type,id,r){
 const cfg=TYPES[type]; const title=r.titel||'Ohne Bezeichnung';
 const status=r.status||''; const meta=[];
 if(r.bereich) meta.push(areas.find(x=>x[0]===r.bereich)?.[1]||r.bereich); if(r.prioritaet)meta.push('Priorität: '+r.prioritaet); if(r.frist)meta.push('Frist: '+r.frist); if(r.naechstePruefung)meta.push('Nächste Prüfung: '+r.naechstePruefung);
 const details=Object.entries(r).filter(([k])=>!['_id','createdAt','updatedAt','createdBy','status','titel','bereich','prioritaet','frist','naechstePruefung'].includes(k)&&r[k]).map(([k,v])=>`<div><b>${esc(labelFor(k))}:</b> ${esc(v)}</div>`).join('');
 return `<article class="qm-item"><div class="qm-item-head"><div><h3>${esc(title)}</h3><div class="qm-meta">${status?`<span class="status-pill status-${esc(status)}">${esc(statusText(status))}</span>`:''}${meta.map(x=>`<span class="badge">${esc(x)}</span>`).join('')}</div></div><span class="qm-small">${r.createdAt?new Date(r.createdAt).toLocaleString('de-DE'):''}</span></div>${details?`<div class="ehsi-detail">${details}</div>`:''}<div class="qm-actions"><button class="button secondary" data-edit="${type}" data-id="${esc(id)}">✏️ Bearbeiten</button><button class="button secondary" data-delete="${type}" data-id="${esc(id)}">🗑 Löschen</button></div></article>`;
}
function labelFor(k){return ({titel:'Titel',bereich:'Bereich',art:'Art',prioritaet:'Priorität',beschreibung:'Beschreibung',ursache:'Ursache',massnahme:'Maßnahme',verantwortlich:'Verantwortlich',frist:'Frist',wirksamkeit:'Wirksamkeitskontrolle',grund:'Grund',auswirkung:'Auswirkung',datum:'Datum',freigegebenAm:'Freigegeben am',geprueftAm:'Geprüft am',naechstePruefung:'Nächste Prüfung',bemerkung:'Bemerkung',teilnehmer:'Teilnehmer / Zielgruppe',inhalt:'Inhalt',version:'Version',status:'Status',link:'Link / Speicherort',bezug:'Bezug'})[k]||k}
function renderList(type){const cfg=TYPES[type], box=$('list'+({pruefung:'Pruef',abweichung:'Abw',massnahme:'Mass',aenderung:'Aend',quellenpruefung:'Quelle',schulung:'Schulung',dokument:'Dok'}[type])); if(!box)return; const rows=Object.entries(data[cfg.path]||{}).map(([id,r])=>[id,r]).sort((a,b)=>String(b[1].createdAt||'').localeCompare(String(a[1].createdAt||''))); box.innerHTML=rows.length?rows.map(([id,r])=>renderItem(type,id,r)).join(''):'<div class="module-note">Noch keine Einträge.</div>';}
function renderAll(){Object.keys(TYPES).forEach(renderList); updateKpis(); renderEvaluation(); renderHistory();}
function updateKpis(){const count=(path,pred)=>Object.values(data[path]||{}).filter(pred).length;$('kpiAbw').textContent=count('qm_abweichungen',r=>!['erledigt'].includes(r.status||'neu'));$('kpiMass').textContent=count('qm_massnahmen',r=>r.status!=='erledigt');$('kpiPruef').textContent=count('qm_pruefungen',r=>r.status!=='erledigt');$('kpiAend').textContent=count('qm_aenderungen',r=>r.status!=='freigegeben');$('kpiQuelle').textContent=count('qm_quellenpruefungen',r=>r.status!=='geprueft');}
function renderEvaluation(){const rows=[];for(const [type,cfg] of Object.entries(TYPES)){const n=Object.keys(data[cfg.path]||{}).length;rows.push(`<div class="qm-item"><b>${esc(cfg.title)}</b><div style="font-size:28px;margin-top:8px">${n}</div><span class="qm-small">Einträge</span></div>`)}$('evaluation').innerHTML=rows.join('');}
function renderHistory(){const rows=Object.values(data.qm_historie||{}).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,30);$('listHistory').innerHTML=rows.length?rows.map(r=>`<article class="qm-item"><b>${esc(r.aktion||'QM-Aktion')}</b><div class="qm-small">${r.createdAt?new Date(r.createdAt).toLocaleString('de-DE'):''} · ${esc(r.benutzer||'Administrator')}</div><div>${esc(r.details||'')}</div></article>`).join(''):'<div class="module-note">Noch keine QM-Historie.</div>';}
async function load(){const a=authState();if(!a.admin){$('qmStatus').textContent='● Administrator-Anmeldung erforderlich';return;}$('qmStatus').textContent='● Administrator angemeldet – QM1 freigegeben';const paths=Object.values(TYPES).map(x=>x.path).concat(['qm_historie','nutzungsereignisse']);const vals=await Promise.all(paths.map(p=>read(p).catch(()=>null)));paths.forEach((p,i)=>data[p]=vals[i]||{});renderAll();}
function fieldHtml(key,label,type,extra,value=''){if(type==='select'){let opts=extra===''?areaOptions():extra.map(x=>`<option value="${x}" ${String(value)===x?'selected':''}>${statusText(x)}</option>`).join(''); if(key==='bereich')opts=areaOptions(); return `<label>${esc(label)}<select name="${key}"><option value="">Bitte wählen …</option>${opts}</select></label>`}if(type==='textarea')return `<label class="full">${esc(label)}<textarea name="${key}">${esc(value)}</textarea></label>`;return `<label class="${extra==='full'?'full':''}">${esc(label)}<input type="${type}" name="${key}" value="${esc(value)}"></label>`;}
function openForm(type,id=null){const cfg=TYPES[type], r=id?(data[cfg.path]?.[id]||{}):{};$('modalTitle').textContent=(id?'Bearbeiten: ':'Neu: ')+cfg.title;$('qmForm').dataset.type=type;$('qmForm').dataset.id=id||'';$('qmForm').innerHTML=cfg.fields.map(f=>fieldHtml(f[0],f[1],f[2],f[3],r[f[0]]||'')).join('')+`<div class="full qm-actions"><button class="button" type="submit">💾 Speichern</button><button class="button secondary" type="button" id="formCancel">Abbrechen</button></div>`;$('qmModal').classList.add('open');$('formCancel').onclick=closeForm;}
function closeForm(){$('qmModal').classList.remove('open');}
async function saveForm(e){e.preventDefault();const f=e.currentTarget,type=f.dataset.type,id=f.dataset.id,cfg=TYPES[type];const obj={};for(const el of f.elements)if(el.name)obj[el.name]=el.value.trim();const old=id?data[cfg.path]?.[id]:null;obj.createdAt=old?.createdAt||new Date().toISOString();obj.updatedAt=new Date().toISOString();obj.createdBy=old?.createdBy||authState().email||'Administrator';if(!obj.status){obj.status=type==='pruefung'?'offen':'neu'}const key=id||('qm_'+Date.now()+'_'+Math.random().toString(36).slice(2,7));try{await write(`${cfg.path}/${encodeURIComponent(key)}`,obj);await write(`qm_historie/${encodeURIComponent('h_'+Date.now()+'_'+Math.random().toString(36).slice(2,6))}`,{aktion:id?'QM-Vorgang geändert':'QM-Vorgang angelegt',details:`${cfg.title}: ${obj.titel||''}`,createdAt:new Date().toISOString(),benutzer:authState().email||'Administrator'});closeForm();await load();}catch(err){alert('Speichern fehlgeschlagen: '+err.message)}}
async function remove(type,id){const a=authState();if(!a.admin){alert('Administrator-Anmeldung erforderlich.');return;}const cfg=TYPES[type];try{await write(`${cfg.path}/${encodeURIComponent(id)}`,null);await write(`qm_historie/${encodeURIComponent('h_'+Date.now()+'_'+Math.random().toString(36).slice(2,6))}`,{aktion:'QM-Vorgang gelöscht',details:`${cfg.title} wurde durch den Administrator gelöscht.`,createdAt:new Date().toISOString(),benutzer:a.email||'Administrator'});await load();}catch(e){alert('Löschen fehlgeschlagen: '+e.message)}}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)return openForm(add.dataset.add);const edit=e.target.closest('[data-edit]');if(edit)return openForm(edit.dataset.edit,edit.dataset.id);const del=e.target.closest('[data-delete]');if(del)return remove(del.dataset.delete,del.dataset.id);});$('qmForm').addEventListener('submit',saveForm);$('modalClose').onclick=closeForm;$('qmModal').addEventListener('click',e=>{if(e.target===$('qmModal'))closeForm()});$('refreshBtn').onclick=load;$('logoutBtn').onclick=()=>{logout();location.href='index.html'};load();
