import{initFirebase,isAdmin,loginAdmin,logoutAdmin,loadAllData,writeData}from"./core.js?v=20260914v16";
const $=id=>document.getElementById(id);let data;
function render(){const list=Object.values(data.einsatzstichworte||{}).sort((a,b)=>(b.priority||0)-(a.priority||0));$("list").innerHTML=list.map(x=>`<div class="manage-row"><div><strong>${x.code||x.id}</strong> – ${x.name||""}<div class="hint">${x.category||""} | Priorität ${x.priority||0}</div><div>${(x.conditions||[]).map(c=>`<span class="badge">${c.questionId} = ${(c.values||[]).join(" / ")}</span>`).join("")||'<span class="hint">keine Bedingungen</span>'}</div></div><button class="secondary edit" data-id="${x.id}">Bearbeiten</button></div>`).join("");document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>edit(b.dataset.id))}
function edit(id){const x=data.einsatzstichworte?.[id]||{};$("id").value=x.id||id;$("code").value=x.code||"";$("name").value=x.name||"";$("category").value=x.category||"brand";$("priority").value=x.priority||0;$("conditions").value=(x.conditions||[]).map(c=>`${c.questionId}=${(c.values||[]).join("|")}`).join("\n")}
function parse(){return $("conditions").value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const i=line.indexOf("=");if(i<1)return null;return{questionId:line.slice(0,i).trim(),values:line.slice(i+1).split("|").map(x=>x.trim()).filter(Boolean)}}).filter(Boolean)}
$("save").onclick=async()=>{try{if(!isAdmin())throw Error("Bitte zuerst als Administrator anmelden.");const id=$("id").value.trim();if(!id)throw Error("ID fehlt.");await writeData(`einsatzstichworte/${id}`,{id,code:$("code").value.trim(),name:$("name").value.trim(),category:$("category").value,priority:Number($("priority").value||0),conditions:parse()});data=await loadAllData();render();alert("Einsatzstichwort gespeichert.")}catch(e){alert(e.message)}};
$("new").onclick=()=>["id","code","name","conditions"].forEach(id=>$(id).value="");
$("loginBtn").onclick=async()=>{const email=prompt("Administrator-E-Mail:");if(email===null)return;const pw=prompt("Administrator-Passwort:");if(pw===null)return;try{await loginAdmin(email,pw);location.reload()}catch(e){alert(e.message)}};
$("logoutBtn").onclick=async()=>{await logoutAdmin();location.reload()};
(async()=>{await initFirebase($("status"));data=await loadAllData();render()})();
