import{initFirebase,isAdmin,loginAdmin,logoutAdmin,loadAllData,writeData,esc,defaultStichworte}from"./core.js?v=20260920v90";
const $=id=>document.getElementById(id);let data;let currentId="";
const catName={brand:"🔥 Brand",thl:"🛠️ THL",abc:"☣️ ABC / Gefahrgut",medizin:"🚑 Medizin",grossschaden:"🚨 Großschaden / Sonderlage"};
function questionsForCat(){return Object.values(data.catalog?.[$("category").value]||{}).filter(q=>q?.id&&q?.text).sort((a,b)=>(Number(a.order)||999999)-(Number(b.order)||999999))}
function optionValues(q){return Array.isArray(q?.options)?q.options.map(String):[]}
function addConditionRow(c={questionId:"",values:[]}){
 const row=document.createElement("div");row.className="condition-row";
 const qLabel=document.createElement("label");qLabel.textContent="Frage";const q=document.createElement("select");q.className="cond-question";q.innerHTML='<option value="">— Frage auswählen —</option>'+questionsForCat().map(x=>`<option value="${esc(x.id)}">${esc(x.text)} [${esc(x.id)}]</option>`).join("");q.value=c.questionId||"";qLabel.appendChild(q);
 const vLabel=document.createElement("label");vLabel.textContent="Antwort(en)";const v=document.createElement("select");v.className="cond-values";v.multiple=true;v.size=4;vLabel.appendChild(v);
 const remove=document.createElement("button");remove.type="button";remove.className="secondary danger small-btn";remove.textContent="✕ Entfernen";remove.onclick=()=>row.remove();
 q.onchange=()=>populateValues(q,v,c.values||[]);populateValues(q,v,c.values||[]);
 row.append(qLabel,vLabel,remove);$("conditionRows").appendChild(row);
}
function populateValues(q,v,selected=[]){const obj=questionsForCat().find(x=>x.id===q.value);const opts=optionValues(obj);v.innerHTML=opts.length?opts.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''):'<option value="*">beliebige Angabe</option>';const wanted=new Set((Array.isArray(selected)?selected:[selected]).map(String));[...v.options].forEach(o=>o.selected=wanted.has(o.value))}
function getConditions(){return [...document.querySelectorAll(".condition-row")].map(row=>{const questionId=row.querySelector(".cond-question")?.value||"";const values=[...row.querySelector(".cond-values")?.selectedOptions||[]].map(o=>o.value);return{questionId,values}}).filter(x=>x.questionId&&x.values.length)}
function render(){
 const list=Object.values(data.einsatzstichworte||{}).sort((a,b)=>(b.priority||0)-(a.priority||0)||String(a.code||a.id).localeCompare(String(b.code||b.id),"de",{numeric:true}));
 $("list").innerHTML=list.map(x=>`<div class="manage-row"><div><strong>${esc(x.code||x.id)}</strong> – ${esc(x.name||"")} <span class="badge">${x.enabled===false?"Vorlage / deaktiviert":"aktiv"}</span><div class="hint">${esc(catName[x.category]||x.category||"")} · Priorität ${Number(x.priority||0)} · ${(x.conditions||[]).length} Bedingung(en)</div>${x.volltext?`<div class="fulltext-preview">Volltext: ${esc(x.volltext)}</div>`:""}</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="secondary edit" data-id="${esc(x.id)}">Bearbeiten</button><button class="secondary danger quick-delete" data-id="${esc(x.id)}">Löschen</button></div></div>`).join("")||'<p class="hint">Noch keine Alarmstichworte vorhanden.</p>';
 document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>edit(b.dataset.id));document.querySelectorAll(".quick-delete").forEach(b=>b.onclick=()=>removeEntry(b.dataset.id));
}
function clearForm(){currentId="";["id","code","name","volltext"].forEach(id=>$(id).value="");$("category").value="brand";$("priority").value=100;$("enabled").value="false";$("conditionMode").value="all";$("conditionRows").innerHTML="";addConditionRow();$("message").textContent="Neues Alarmstichwort."}
function edit(id){const x=data.einsatzstichworte?.[id];if(!x)return;currentId=id;$("id").value=x.id||id;$("code").value=x.code||"";$("name").value=x.name||"";$("category").value=x.category||"brand";$("priority").value=x.priority??100;$("enabled").value=x.enabled===false?"false":"true";$("volltext").value=x.volltext||"";$("conditionMode").value=x.conditionMode||"all";$("conditionRows").innerHTML="";(x.conditions||[]).forEach(c=>addConditionRow(c));if(!(x.conditions||[]).length)addConditionRow();window.scrollTo({top:0,behavior:"smooth"})}
async function removeEntry(id){if(!isAdmin()){alert("Bitte zuerst als Administrator anmelden.");return}const x=data.einsatzstichworte?.[id];if(!x)return;if(!confirm(`Alarmstichwort ${x.code||id} wirklich löschen?`))return;try{await writeData(`einsatzstichworte/${id}`,null);data=await loadAllData();render();if(currentId===id)clearForm();$("message").textContent="Alarmstichwort gelöscht."}catch(e){alert(e.message)}}
$("seed").onclick=async()=>{try{if(!isAdmin())throw Error("Bitte zuerst als Administrator anmelden.");if(!confirm("Die Grundvorlage legt B1–B3, G1–G3, TH1–TH3 und SL als deaktivierte Vorlagen an bzw. aktualisiert diese. Andere Stichworte bleiben erhalten. Fortfahren?"))return;for(const [id,x] of Object.entries(defaultStichworte))await writeData(`einsatzstichworte/${id}`,x);data=await loadAllData();render();$("seedStatus").textContent="Grundvorlage übernommen. Jetzt Bedingungen festlegen und die gewünschten Stichworte aktivieren."}catch(e){alert(e.message)}};
$("addCondition").onclick=()=>addConditionRow();$("category").onchange=()=>{const old=getConditions();$("conditionRows").innerHTML="";old.forEach(c=>addConditionRow(c));if(!old.length)addConditionRow()};$("new").onclick=clearForm;$("delete").onclick=()=>currentId?removeEntry(currentId):alert("Kein bestehendes Stichwort ausgewählt.");
$("save").onclick=async()=>{try{if(!isAdmin())throw Error("Bitte zuerst als Administrator anmelden.");const id=$("id").value.trim();if(!id)throw Error("ID fehlt.");const conditions=getConditions();const value={id,code:$("code").value.trim()||id,name:$("name").value.trim(),category:$("category").value,priority:Number($("priority").value||0),enabled:$("enabled").value==="true",conditionMode:$("conditionMode").value,conditions,volltext:$("volltext").value.trim()};await writeData(`einsatzstichworte/${id}`,value);data=await loadAllData();currentId=id;render();$("message").textContent="Alarmstichwort gespeichert."}catch(e){alert(e.message)}};
$("loginBtn").onclick=async()=>{const email=prompt("Administrator-E-Mail:");if(email===null)return;const pw=prompt("Administrator-Passwort:");if(pw===null)return;try{await loginAdmin(email,pw);location.reload()}catch(e){alert(e.message)}};$("logoutBtn").onclick=async()=>{await logoutAdmin();location.reload()};
(async()=>{await initFirebase($("status"));data=await loadAllData();render();clearForm()})();
